import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import os

# 1. Load the features generated by the previous script
FILE_PATH = 'e:/Excel Datasets/ikea_advanced_features.csv'

if not os.path.exists(FILE_PATH):
    print(f"Error: {FILE_PATH} not found. Please run 'ikea_advanced_ds.py' first!")
    exit()

df = pd.read_csv(FILE_PATH)

# Cleanup: Drop non-numeric IDs for ML
features = df.select_dtypes(include=[np.number]).drop(columns=['product_id', 'top_seller_pct'], errors='ignore')
target = df['top_seller_pct']

# --- 1.5 DEFINE BUSINESS CLUSTER NAMES ---
def name_clusters(row):
    # Based on avg_price and characteristics
    p = row['avg_price']
    v = row['volume_est']
    if p < 1000: return 'Budget Entry (High Volume)'
    if p < 1500: return 'Reliable Basics'
    if p > 6000: return 'Premium Flagships'
    if p > 3000: return 'Mid-Range Statement'
    return 'Standard Portfolio'

df['cluster_name'] = df.apply(name_clusters, axis=1)

# Add Business Strategy to hover
def get_strategy(row):
    if 'Budget' in row['cluster_name']: return "Strategy: Drive volume with mass promotions"
    if 'Premium' in row['cluster_name']: return "Strategy: Exclusive marketing & premium store placement"
    if row['is_anomaly'] == 1: return "Strategy: INVESTIGATE - Potential new niche or price error"
    return "Strategy: Maintain steady stock and reviews"

df['business_strategy'] = df.apply(get_strategy, axis=1)

# --- 2. TRAIN POPULARITY PREDICTOR (XGBoost) ---
print("\n--- Training Popularity Predictor (XGBoost) ---")
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

model = XGBRegressor(n_estimators=100, max_depth=5, learning_rate=0.1, objective='reg:squarederror')
model.fit(X_train, y_train)

preds = model.predict(X_test)
print(f"Model R2 Score: {r2_score(y_test, preds):.4f}")

# Feature Importance
importance = pd.DataFrame({'feature': features.columns, 'importance': model.feature_importances_})
importance = importance.sort_values('importance', ascending=False)
print("\nTop Factors Driving IKEA Popularity:")
print(importance.head(5))

# --- 3. INTERACTIVE 3D VISUALIZATION ---
print("\n--- Generating 3D Product Galaxy ---")
# Sample for performance if needed, but 40k is usually okay for Plotly
df_plot = df.sample(min(5000, len(df))) 

fig = px.scatter_3d(
    df_plot, 
    x='avg_price', 
    y='avg_rating', 
    z='volume_est',
    color='cluster_name', # Use human names
    size='total_reviews',
    hover_name='product_id',
    hover_data=['business_strategy', 'country_count'],
    title='IKEA Product Galaxy Map: Your Business at a Glance',
    labels={'avg_price': 'Price ($)', 'avg_rating': 'Rating (Stars)', 'volume_est': 'Physical Size'},
    template='plotly_dark'
)

# Customize the layout for a premium feel
fig.update_layout(
    scene = dict(
        xaxis = dict(backgroundcolor="rgb(20, 20, 20)", gridcolor="white", showbackground=True),
        yaxis = dict(backgroundcolor="rgb(20, 20, 20)", gridcolor="white", showbackground=True),
        zaxis = dict(backgroundcolor="rgb(20, 20, 20)", gridcolor="white", showbackground=True),
    ),
    margin=dict(l=0, r=0, b=0, t=40)
)

# Save the visualization as HTML
output_viz = 'e:/Excel Datasets/ikea_product_galaxy.html'
fig.write_html(output_viz)
print(f"Interactive Visualization saved to: {output_viz}")

# --- 4. RADAR CHART (Cluster Profiles) ---
print("\n--- Generating Cluster Profile Radar Chart ---")
cluster_summary = df.groupby('cluster_name').mean(numeric_only=True).reset_index()

# Select metrics for the radar chart
metrics = ['avg_price', 'avg_rating', 'top_seller_pct', 'country_count', 'volume_est']
# Normalize for the chart
for m in metrics:
    cluster_summary[m] = cluster_summary[m] / (cluster_summary[m].max() + 1e-6)

radar_fig = go.Figure()

for i, row in cluster_summary.iterrows():
    radar_fig.add_trace(go.Scatterpolar(
        r=[row[m] for m in metrics],
        theta=metrics,
        fill='toself',
        name=row['cluster_name']
    ))

radar_fig.update_layout(
  polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
  showlegend=True,
  title="Strategic Portfolio View: Cluster Characteristics",
  template='plotly_dark'
)

output_radar = 'e:/Excel Datasets/ikea_cluster_radar.html'
radar_fig.write_html(output_radar)
print(f"Strategic Radar Chart saved to: {output_radar}")

print("\nAll Pro Suite components generated successfully!")
